project('pdcurses', 'c', version: '4.5.4')

pdcurses_inc = include_directories('.', 'pdcurses', 'vt')

pdcurses_sources = files(
    'pdcurses/addch.c',
    'pdcurses/addchstr.c',
    'pdcurses/addstr.c',
    'pdcurses/attr.c',
    'pdcurses/beep.c',
    'pdcurses/bkgd.c',
    'pdcurses/border.c',
    'pdcurses/clear.c',
    'pdcurses/color.c',
    'pdcurses/debug.c',
    'pdcurses/delch.c',
    'pdcurses/deleteln.c',
    'pdcurses/getch.c',
    'pdcurses/getstr.c',
    'pdcurses/getyx.c',
    'pdcurses/inch.c',
    'pdcurses/inchstr.c',
    'pdcurses/initscr.c',
    'pdcurses/inopts.c',
    'pdcurses/insch.c',
    'pdcurses/insstr.c',
    'pdcurses/instr.c',
    'pdcurses/kernel.c',
    'pdcurses/keyname.c',
    'pdcurses/mouse.c',
    'pdcurses/move.c',
    'pdcurses/outopts.c',
    'pdcurses/overlay.c',
    'pdcurses/pad.c',
    'pdcurses/panel.c',
    'pdcurses/printw.c',
    'pdcurses/refresh.c',
    'pdcurses/scanw.c',
    'pdcurses/scr_dump.c',
    'pdcurses/scroll.c',
    'pdcurses/slk.c',
    'pdcurses/termattr.c',
    'pdcurses/terminfo.c',
    'pdcurses/touch.c',
    'pdcurses/util.c',
    'pdcurses/window.c',
    'vt/pdcclip.c',
    'vt/pdcdisp.c',
    'vt/pdcgetsc.c',
    'vt/pdckbd.c',
    'vt/pdcscrn.c',
    'vt/pdcsetsc.c',
    'vt/pdcutil.c',
)

pdcurses_lib = static_library('pdcurses_vt', pdcurses_sources,
                              include_directories: pdcurses_inc,
                              c_args: ['-DPDC_WIDE=1', '-DPDC_FORCE_UTF8=1', '-DPDC_VT=1'])

pdcurses_dep = declare_dependency(include_directories: pdcurses_inc,
                                  link_with: pdcurses_lib)
