project('pdcurses', 'c', version: '4.5.4')

pdcurses_inc = include_directories('.', 'common', 'wincon')

pdcurses_sources = files(
    'common/addch.c',
    'common/addchstr.c',
    'common/addstr.c',
    'common/attr.c',
    'common/beep.c',
    'common/bkgd.c',
    'common/border.c',
    'common/clear.c',
    'common/color.c',
    'common/debug.c',
    'common/delch.c',
    'common/deleteln.c',
    'common/getch.c',
    'common/getstr.c',
    'common/getyx.c',
    'common/inch.c',
    'common/inchstr.c',
    'common/initscr.c',
    'common/inopts.c',
    'common/insch.c',
    'common/insstr.c',
    'common/instr.c',
    'common/kernel.c',
    'common/keyname.c',
    'common/mouse.c',
    'common/move.c',
    'common/outopts.c',
    'common/overlay.c',
    'common/pad.c',
    'common/panel.c',
    'common/printw.c',
    'common/refresh.c',
    'common/scanw.c',
    'common/scr_dump.c',
    'common/scroll.c',
    'common/slk.c',
    'common/termattr.c',
    'common/terminfo.c',
    'common/touch.c',
    'common/util.c',
    'common/window.c',
    'wincon/pdcclip.c',
    'wincon/pdcdisp.c',
    'wincon/pdcgetsc.c',
    'wincon/pdckbd.c',
    'wincon/pdcscrn.c',
    'wincon/pdcsetsc.c',
    'wincon/pdcutil.c',
)

pdcurses_lib = static_library('pdcurses', pdcurses_sources,
                              include_directories: pdcurses_inc,
                              c_args: ['-DPDC_WIDE'])

pdcurses_dep = declare_dependency(include_directories: pdcurses_inc,
                                  link_with: pdcurses_lib)
